name: Release
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build (linux)
      env:
        GOOS: linux
        GOARCH: amd64
      run: make

    - name: Build (darwin)
      env:
        GOOS: darwin
        GOARCH: amd64
      run: make

    - name: Build (windows)
      env:
        GOOS: windows
        GOARCH: amd64
      run: make

    - name: Zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq tls-issue-repro.zip bin

    - name: Publish
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: tls-issue-repro.zip
